name: Test maker

on:
  push:
    branches: [ 3.0.x ]
  pull_request:
    branches: [ 3.0.x ]

env:
  PHP_VERSION: 8.1
  COMPOSER_ALLOW_SUPERUSER: '1' # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.5.x', '10.0.x']
        php-versions: ['8.1']
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Verify MySQL connection from container
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
          mysql --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot --protocol=tcp -e "CREATE DATABASE IF NOT EXISTS drupal10;"
          mysql --host 172.18.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -proot --protocol=tcp -e "USE drupal10; select user();"
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install Composer dependencies
        run: composer install
      - name: Site Setup
        run:
          echo "export PATH=$PATH:$GITHUB_WORKSPACE/vendor/bin" >> ~/.bash_profile
          source ~/.bash_profile
          drush si -y --site-name=maker
          drush en -y maker
          drush theme:enable maker_theme
          drush config-set -y system.theme default maker_theme

      - name: Check coding standards
        run: |
          ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,install,js web/modules/contrib/maker
          ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,install,js web/themes/contrib/maker_theme
